# Generated by Django 3.0.7 on 2020-07-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20200710_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
